name: Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    permissions:
      actions: read
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v3
    # - uses: ouzi-dev/commit-status-updater@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
    - run: npm run build-dist
    - run: npm test
    # - if: always()
    #   uses: ouzi-dev/commit-status-updater@v2
    #   with:
    #     status: "${{ job.status }}"
